name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      # Download and install Hadolint
      - name: Download Hadolint for Windows
        run: wget https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64.exe -O hadolint.exe


      # Run Hadolint against Dockerfile
      - name: Run Hadolint
        run: .\hadolint.exe Dockerfile

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
