name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Build Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    # Run the Docker container
    - name: Run the Docker container
      run: |
        docker run --env LAT="5.902785" \
                   --env LONG="102.754175" \
                   --env API_KEY=${{ secrets.API_KEY }} \
                   img_tp2
