name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag img_tp2:$(date +%s)

    - name: Use API key
      run: node index.js
      env:
         API_KEY: ${{ secrets.API_KEY }}
