name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Construire l'image Docker
        run: |
          docker build -t img_pour_tp3 .  
          docker images                       

      - name: Publier sur Azure Container Registry
        if: github.ref == 'refs/heads/main' 
        run: |
          az acr login --name ${{ secrets.REGISTRY_LOGIN_SERVER }}
          docker tag img_pour_tp3 ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REGISTRY_USERNAME }}/img_pour_tp3:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REGISTRY_USERNAME }}/img_pour_tp3:latest

      - name: Déployer sur Azure Container Instance
        if: github.ref == 'refs/heads/main' 
        run: |
          az container create --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.ACI_NAME }} --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REGISTRY_USERNAME }}/img_pour_tp3:latest --dns-name-label devops-20200384 --location francecentral --cpu 1 --memory 1 --ports 8081 --registry-login-server ${{ secrets.REGISTRY_LOGIN_SERVER }} --registry-username ${{ secrets.REGISTRY_USERNAME }} --registry-password ${{ secrets.REGISTRY_PASSWORD }}
